update my company website domain to Jjlmedia.com
Create my company email address Jamesloughman@jjlmedia.com
Assign my role with JJL Media as CEO 
Assign me as super admin
Remove any other role positions with JJL Media
